Lab 02
prianechka/BMSTU-SD pull request #3
Opened 2022-05-23 16:23 UTC by prianechka

2022-05-23 16:25 UTC, Sych474 requested changes
- [ ] Поправить интерфейсы в слое хранения данных (из конкретных юзкейсов в общие методы). 
- перенести коннекшн в слой хранения данных. 
- добавить картинки в ридми.

После исправлений может быть сдана без присутствия на лабе.

2022-05-25 20:31 UTC, prianechka commented
Исправил всё.

2022-05-25 21:19 UTC, prianechka commented
@Sych474

2022-05-26 16:24 UTC, Sych474 approved these changes

2022-05-26 16:24 UTC, merged