Add lab_04 v1
prianechka/BMSTU-SD pull request #5
Opened 2022-09-06 12:21 UTC by prianechka

@Sych474 

Это 4 лаба: написание репозиториев + простейшие тесты к ней.

2022-09-10 18:44 UTC, Sych474 requested changes

2022-09-10 18:44 UTC, Sych474 commented on src/logic/studentController.cpp
> +                                   std::string studentNumber, int webID)
Что такое webID?

2022-09-10 18:44 UTC, Sych474 commented on src/logic/studentController.cpp
> +    this->repository->changeStudent(id, tmpDTO);
Возможно возникновение ошибок в репозитории? Тут нет никаких обработок ошибок (к примеру если попытаетесь изменить группу студента которого нет в БД)

2022-09-10 18:44 UTC, Sych474 commented on src/logic/studentController.cpp
> +    this->repository->changeStudent(id, tmpDTO);
Аналогично по поводу обработки ошибок в прочих случаях.

2022-09-10 18:44 UTC, Sych474 commented on src/logic/thingController.cpp
> +        srcRoomID = NOT_FOUND;
Выглядит как костыль, не понятно зачем менять это значение таким образом, поясните.

2022-09-11 10:41 UTC, prianechka commented on src/logic/studentController.cpp
> +                                   std::string studentNumber, int webID)
У каждого студента есть свой аккаунт для входа. И соотношение между аккаунтом студента и студентом 1 к 1. Поэтому в БД хранится в сущности студента также и вторичный ключ аккаунта. При добавлении студента нужно также добавить ему аккаунт для входа в систему. И поэтому также нужно передавать webID.

2022-09-11 10:42 UTC, prianechka commented on src/logic/studentController.cpp
> +    this->repository->changeStudent(id, tmpDTO);
Всё добавил-исправил, теперь кидаю ошибки

2022-09-11 10:42 UTC, prianechka commented on src/logic/thingController.cpp
> +        srcRoomID = NOT_FOUND;
Да, это костыль. Теперь его нет :)

2022-09-16 17:12 UTC, Sych474 commented on src/logic/studentController.cpp
> +                                   std::string studentNumber, int webID)
Ок, но почему название webID, а не скажем accountId или что-то подобное?

2022-09-16 17:15 UTC, Sych474 requested changes

2022-09-16 17:15 UTC, Sych474 commented on src/tests/test_main.cpp
> +int main(int argc, char *argv[])
Не оставляйте неиспользуемый закомментированный код

2022-09-16 17:15 UTC, Sych474 commented on src/tests/test_main.cpp
> +}
А что делать, если тестов на 10к строк? распределите их на несколько файлов.

2022-09-16 17:17 UTC, prianechka commented on src/tests/test_main.cpp
> +int main(int argc, char *argv[])
Так это же тесты, иногда их надо запускать, иногда приложение запускать. Они как раз-таки и используются

2022-09-16 17:27 UTC, prianechka commented on src/tests/test_main.cpp
> +}
Done

2022-09-16 17:28 UTC, prianechka commented on src/logic/studentController.cpp
> +                                   std::string studentNumber, int webID)
На автомате :) Исправил.

2022-09-16 17:39 UTC, Sych474 commented on src/tests/test_main.cpp
> +int main(int argc, char *argv[])
Тесты должны быть отдельным приложением и собираться отдельно

2022-09-16 17:40 UTC, Sych474 commented on src/tests/test_main.cpp
> +int main(int argc, char *argv[])
Иначе у вас получается какая-то очень не очень штука с кодом. 

Как автотесты запускать? А если потом надо сразу автоматически запускаемые файлы собрать? В общем - нужно два разных проекта - один тестовый, другой основной.

2022-09-16 17:41 UTC, Sych474 commented on src/tests/test_main.cpp
> +int main(int argc, char *argv[])
Ну для C++ это грубо говоря два файла и либо в make две цели, либо проекты в IDE, если в ней делаете.

2022-09-16 17:48 UTC, Sych474 approved these changes

2022-09-16 17:48 UTC, merged